### ISSUE TITLE
AxeReporter: Write results as an HTML file

### ISSUE THREAD

**Issue by jonreding2010** [dequelabs/axe-core-maven-html#103]
It would be handy for the Axe scan to be able to be configured to an HTML doc.
Having the html doc would be easier for developers to use.
The Axe C# equivalent has this functionality: https://github.com/TroyWalshProf/SeleniumAxeDotnet/blob/master/Selenium.Axe/Selenium.Axe/HtmlReport.cs

**Comment by jonreding2010** [comment]
I have begun work on this but having issues getting the unit tests to work. 
If I can get some assistance to get the unit tests working I'll be able to finish up and submit the code.

Right now I get this error: "The path to the driver executable must be set by the webdriver.chrome.driver system property"

**Comment by jonreding2010** [comment]
@jeeyyy look into #118 if you want. 
I'm finishing up my unit tests but if you wish to assist please do.

**Comment by jonreding2010** [comment]
@jeeyyy I've updated my PR and added unit tests. There are currently 2 TODOs that I have commented on in the PR. 
Let me know if you have any questions or feedback

**Comment by kishkk84** [comment]
> I have begun work on this but having issues getting the unit tests to work.
> If I can get some assistance to get the unit tests working I'll be able to finish up and submit the code.
> 
> Right now I get this error: "The path to the driver executable must be set by the webdriver.chrome.driver system property"

Hey @jonreding2010 How did you fix the "path to the driver executable" error? Please share the resolution.
Thanks
Kishore
