### ISSUE TITLE
AxeReporter is not appending nodes in axe results

### ISSUE THREAD

**Issue by tsharma-indeed** [dequelabs/axe-core-maven-html#111]
https://github.com/tsharma-indeed/axe-core-maven-html/blob/develop/src/main/java/com/deque/html/axecore/selenium/AxeReporter.java#L160

The below line has an issue. This if statement will never get executed and hence, nodes willl not get appended to the axe results
 `if (element.getNodes() != null && element.getNodes().isEmpty())`

**Fix:** `!element.getNodes().isEmpty()` Not (!) should be added to this statement so that further if statements will able to hit

**Comment by padmavemulapati** [comment]
@SantoshDeque , please take care of this ticket

**Comment by padmavemulapati** [comment]
Seeing some issue here -
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.908 s
[INFO] Finished at: 2021-01-08T19:04:33+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (vulnerability-checks) on project selenium: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
as per Adam, he pushed a fix for this, so once the fix merged , will check once again and will close the ticket

**Comment by SantoshDeque** [comment]
Verified in latest develop branch and issue is fixed now.
