### ISSUE TITLE
"No elements found for include in page context " error appearing when `include` having multiple web elements

### ISSUE THREAD

**Issue by padmavemulapati** [dequelabs/axe-core-maven-html#115]
Steps to reproduce:
on axe-core-maven-html: when tested for include method on multiple web elements
`AxeBuilder().include(Arrays.asList("div", "h1")).analyze(webDriver);`
results are blank. and giving "No elements found for include in page context"
![image (15)](https://user-images.githubusercontent.com/47409579/99975698-961b1b00-2dc8-11eb-937a-7e2963d4064b.png)

**Comment by AdnoC** [comment]
In oder to include multiple elements you call `include` multiple times with each individual selector. `include` takes a list of selectors solely to select elements inside `iframe`s.

**Comment by padmavemulapati** [comment]
Discussed with Adam, 
with the change in the test code snippet:
` Results result = new AxeBuilder().include(Arrays.asList("div")).include(Arrays.asList("h1")).analyze(webDriver);` instead 
`AxeBuilder().include(Arrays.asList("div", "h1")).analyze(webDriver);`
its giving the expected results.
