### ISSUE TITLE
The metadata for home page etc (urls) are wrong in maven repo

### ISSUE THREAD

**Issue by jeeyyy** [dequelabs/axe-core-maven-html#119]
https://search.maven.org/artifact/com.deque.html.axe-core/selenium

**Comment by SantoshDeque** [comment]
The urls for Home page and Source code are pointing to deprecated urls 
Home page: https://github.com/dequelabs/axe-selenium-java
Source code https://github.com/dequelabs/axe-selenium-java

Shouldn't they be pointing to below urls?
Home page: https://github.com/dequelabs/axe-core-maven-html
Source Code: https://github.com/dequelabs/axe-core-maven-html

@AdnoC , could you please confirm

**Comment by AdnoC** [comment]
That is correct. However it won't update until we do a new release.

**Comment by SantoshDeque** [comment]
Now the home page and source code urls are pointing correctly for latest version(4.1.2)
Home page: https://github.com/dequelabs/axe-core-maven-html
Source Code: https://github.com/dequelabs/axe-core-maven-html

@AdnoC , could you please confirm if these urls should be updated for older versions(for ex: 4.1.1) also?

**Comment by SantoshDeque** [comment]
Discussed with @AdnoC, changes seems to be applied only to 4.1.2
