### ISSUE TITLE
Upgrading to 3.1

### ISSUE THREAD

**Issue by ofoxborn** [dequelabs/axe-core-maven-html#131]
Hello,

We want to upgrade to version 3.1 . We understand that it has been moved to [axe-core-maven-html]. 
We cannot find the deployed jar in maven repos. Can you please let us know where to get it from? 

We searched for a dependency to look like this:

`<dependency>
    <groupId>com.deque.html.axe-core</groupId>
    <artifactId>selenium</artifactId>
    <version>3.1</version>
    <scope>test</scope>
</dependency>`

Thank you,

**Comment by AdnoC** [comment]
It looks like we never published 3.1. Are you willing to update to 4.0?

**Comment by ofoxborn** [comment]
Yes, we are willing to update, but at a later time, not yet. 
We'd rather upgrade to 3.1 if possible, since its a smaller upgrade.

**Comment by jeeyyy** [comment]
@ofoxborn it looks like the release for [v3.1](https://github.com/dequelabs/axe-core-maven-html/releases/tag/v3.1.0) did not make it to maven central. 

Are you able to install from the tag/ release above, until you make a decision to update to 4.0 (which is in Maven repository.

Feel free to open this issue, if you are unable to install from the above tag/ release.
