### ISSUE TITLE
Help URL is not URL pointing to help in AxeReporter

### ISSUE THREAD

**Issue by petja-laitila** [dequelabs/axe-core-maven-html#142]
Line 153 in AxeReporter.java

**Comment by kishkk84** [comment]
Line 153 in AxeReporter.java has `element.getHelp` instead of  `element.getHelpUrl()`. This needs to be corrected.

**Comment by kishkk84** [comment]
I raised a PR to fix this [#144](https://github.com/dequelabs/axe-core-maven-html/pull/144)

**Comment by SantoshDeque** [comment]
Verified in latest develop branch and changes are working fine.
![Screenshot (315)](https://user-images.githubusercontent.com/45222788/118820083-9279d400-b8d3-11eb-9e9b-1ffd25685441.png)

**Comment by michael-siek** [comment]
closing no docs required
