### ISSUE TITLE
chore: upgrade to use `axe-core@4.3.2`

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-maven-html#172]
Expectation: upgrade to use axe-core@4.3.2 and axe-core#runPartial()

Actual: currently uses `axe-core@4.2.x`

**Comment by varivoda** [comment]
@michael-siek Hi!

Could you please clarify, what are we waiting for here and can I help with this deploying of new version somehow?

**Comment by tsharma-indeed** [comment]
@AdnoC Appreciate if we can upgrade this library asap. It's been 22 days when the new version had launched!

**Comment by varivoda** [comment]
@nloding @AdnoC Hi there!

Do you have any ETA according to this issue? I'm trying to understand how should I plan the sprint in my team)

Thank you!

**Comment by tsharma-indeed** [comment]
@michael-siek @AdnoC @nloding Guys any update on this!

**Comment by AdnoC** [comment]
Hi! We've got a lot of integrations and updating each takes time. In this release of axe-core specifically we took time to ensure the use of `axe.runPartial` and `axe.finishRun` were correct and guaranteed the cross-domain isolation those functions were intended for.

We're just getting to Java. Should be soon.

**Comment by AdnoC** [comment]
@varivoda @tsharma-indeed Just wanted to ping you to inform you that axe-core@4.3.3 has been merged.

**Comment by tsharma-indeed** [comment]
Yay!!! Thanks a bunch, @AdnoC. Appreciate it.

**Comment by varivoda** [comment]
@AdnoC Thanks a lot!

Could you please clarify, who is responsible for deploying the new version to maven.central and when this might be done? Thanks!

**Comment by AdnoC** [comment]
Releasing is done for all our integrations at once so it is a team effort. Unfortunately I can't say anything more than should be soon.

**Comment by SantoshDeque** [comment]
Upgrade to axe-core@4.3.3 is completed
