### ISSUE TITLE
add a sub-module `dequeUtilities` to monorepo

### ISSUE THREAD

**Issue by Zidious** [dequelabs/axe-core-maven-html#207]
**Why?** 

Both Selenium and Playwright integrations use the same classes to map the JSON properties used in axe-core: 

<img width="296" alt="image" src="https://user-images.githubusercontent.com/41127686/158190338-8d0efa58-d79d-407d-8cd7-6499e2fd284c.png">

Move the classes used in the both packages to a new module `dequeUtilities` which will import them as a dependency to same them having duplicate classes 

- [x] Add new submodule
- [x] Refactor Selenium to use new module
- [x] Refactor playwright to use new module

**Comment by Zidious** [comment]
Ref: https://github.com/dequelabs/axe-core-maven-html/pull/252

**Comment by somaalapati** [comment]
@Zidious Is this testable by QA or its a dev thingy?

**Comment by Zidious** [comment]
Sorry @somaalapati dev task, did not mean to close and put it into QA

**Comment by somaalapati** [comment]
@Zidious No worries. Normally we request another developer in the team to verify these types of tickets. PO can take care of these type of tickets.
@michael-siek Can you please verify this ticket?
