### ISSUE TITLE
Is org.json actually used as a dependency?

### ISSUE THREAD

**Issue by data-enabler** [dequelabs/axe-core-maven-html#226]
`org.json` is listed as a dependency for the Selenium library, but I don't see any references in the codebase.
The library seemed to work just fine (including JSON output) when I excluded it.

**Comment by Zidious** [comment]
Hey @data-enabler,

Looking at this, it appears this may of been used previously and is not longer used and was just not removed. We will open a PR to get this removed.

Thank you for finding this!

**Comment by Zidious** [comment]
closing, no docs required
