### ISSUE TITLE
[BUG] I am trying to use AxeBuilder for accessibility testing, its giving me dependency resolution issue 

### ISSUE THREAD

**Issue by pranesh517** [dequelabs/axe-core-maven-html#238]
I am trying to use AxeBuilder for accessibility testing and for that i added below gradle dependency:
implementation group: 'com.deque.html.axe-core', name: 'playwright', version: '4.4.1'

After running test with AxeResults axeResults = new AxeBuilder(page).analyze();
Getting below error:
Execution failed for task ':compileJava'.

Could not resolve all files for configuration ':compileClasspath'.
Could not resolve commons-codec:commons-codec:20041127.091804.
Required by:
project :
project : > com.deque.html.axe-core:playwright:4.4.1
> Could not resolve commons-codec:commons-codec:20041127.091804.
> inconsistent module metadata found. Descriptor: commons-codec:commons-codec:1.3 Errors: bad version: expected='20041127.091804' found='1.3'

I am using Playwright version 1.25.0.
Below is my build.gradle:
plugins {
id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
mavenCentral()
}

dependencies {
testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
// https://mvnrepository.com/artifact/com.microsoft.playwright/playwright
implementation group: 'com.microsoft.playwright', name: 'playwright', version: '1.25.0'
implementation group: 'com.deque.html.axe-core', name: 'playwright', version: '4.4.1'
}

test {
useJUnitPlatform()
}

**Comment by Zidious** [comment]
Hey @pranesh517,

Thank you for reporting this issue, we will investigate and get back to you as soon as possible.

**Comment by Zidious** [comment]
I was able to replicate this issue using Gradle. Maven however it is able to locate the dependency without issues. Looking at the [maven2 repository ](https://repo.maven.apache.org/maven2/commons-codec/commons-codec/) with the `commons-codec` dependency: [version: 20041127.091804](https://repo.maven.apache.org/maven2/commons-codec/commons-codec/20041127.091804/commons-codec-20041127.091804.pom) shows as `1.3`. 

Recently we updated our dependencies for all packages, specifically [playwright's pom.xml](https://github.com/dequelabs/axe-core-maven-html/blob/develop/playwright/pom.xml#L265-L269). On Monday, I will raise this up with the team to cut a patch release which should resolve this issue.

**Comment by Ben-Waters** [comment]
Sounds great! This is also impacting us.

**Comment by SantoshDeque** [comment]
Verified with 'playwright', version: '4.4.2' using Gradle and maven,  dependency issue is resolved. PFA screenshots
1)Using Gradle
<img width="791" alt="Screenshot 2022-10-07 at 5 35 22 PM" src="https://user-images.githubusercontent.com/45222788/194549509-94232f55-3f8b-42f0-93bc-c7655417c65f.png">

2)Using Maven
<img width="757" alt="Screenshot 2022-10-07 at 5 54 33 PM" src="https://user-images.githubusercontent.com/45222788/194552665-b567ab24-f785-4c2f-8732-e90daf8f8f91.png">

**Comment by Zidious** [comment]
Hello all, 

Closing this issue as the dependency issue is resolved. 

Please let me know if you run into any other issues.
