### ISSUE TITLE
update to use axe-core version 4.4.3

### ISSUE THREAD

**Issue by michael-siek** [dequelabs/axe-core-maven-html#239]
We should upgrade both playwright and selenium to use the latest version of axe-core which is axe-core v4.4.3

**Comment by SantoshDeque** [comment]
Verified in latest "Develop" branch, axe-core version has been updated to v4.4.3 for playwright and selenium. PFA screenshots
1)Playwright:
<img width="1353" alt="Screenshot 2022-09-28 at 12 31 27 PM" src="https://user-images.githubusercontent.com/45222788/192711278-4073a79f-67fe-44ef-9ebf-ec2dca04dccf.png">

2)Selenium:
<img width="1361" alt="Screenshot 2022-09-28 at 12 34 42 PM" src="https://user-images.githubusercontent.com/45222788/192711340-324e1c24-2d97-407c-a7b2-27f38f5827b4.png">
