### ISSUE TITLE
Update Selenium documentation to be a bit more descriptive and provide examples of usage

### ISSUE THREAD

**Issue by Zidious** [dequelabs/axe-core-maven-html#284]
At the moment our Selenium docs are lacking a bit of explanation and examples of usage. 

We should update the Selenium docs to match the  [Playwright Java](https://github.com/dequelabs/axe-core-maven-html/tree/develop/playwright) documentation.

**Comment by padmavemulapati** [comment]
Validated, [Selenium ](https://github.com/dequelabs/axe-core-maven-html/tree/develop/selenium), readme updation , trying all the examples and all are working as expected
