### ISSUE TITLE
axe is not defined

### ISSUE THREAD

**Issue by dramu** [dequelabs/axe-core-maven-html#32]
We are trying to integrated axe framework with existing Selenium Test cases. It is working perfectly but sometimes test cases are getting failed due to below error,

org.openqa.selenium.WebDriverException: javascript error: axe is not defined
JavaScript stack:
ReferenceError: axe is not defined
at eval (eval at executeAsyncScript (:457:5), <anonymous>:3:20)
at eval (eval at executeAsyncScript (:457:5), <anonymous>:3:86)
at executeAsyncScript (<anonymous>:457:26)
at <anonymous>:473:29
at callFunction (<anonymous>:361:33)
at <anonymous>:371:23
at <anonymous>:372:3

Please help me if you already have a fix for it. Thanks in advance.

**Comment by dastewa** [comment]
Any updates on this? Running into the same error.

**Comment by AdnoC** [comment]
The only way I can reproduce your error is if I pass an improper axe-core source code (e.g. a blank file). Can you ensure that you are passing axe-core correctly? If you update to 4.0 axe-core source code is automatically included.

**Comment by jeeyyy** [comment]
Closing this issue as we have not heard back. Feel free to open it.
