### ISSUE TITLE
Add frame-tested for unloaded iframes

### ISSUE THREAD

**Issue by straker** [dequelabs/axe-core-maven-html#323]
The [change was made to our javascript APIs](https://github.com/dequelabs/axe-core-npm/pull/752) but needs to be ported to here.

**Comment by padmavemulapati** [comment]
@AdnoC , Is this ticket QA-Required?  If yes please add few QA-Note

**Comment by padmavemulapati** [comment]
Verified with the latest axe-core-maven-html_48.0` version ,
created a test file for unloaded iframes(lazy loaded iframes)

1. axe-core-maven-html_playwright is working fine with the lazy loaded iframes it is not hanging and giving `frame-title` violations and `frame-tested` incomplete results

Test script:

```
 @Test
    public void scanPageAndSaveResultsToJsonFileTest() throws IOException {
        String reportName = "iframesTest.json";
        page.navigate("http://localhost:8081/iframesfixture.html");
        AxeBuilder axeBuilder = new AxeBuilder(page);
        AxeResults axeResults = axeBuilder.analyze();
        Reporter reporter = new Reporter().JSONStringify(axeResults, reportName);
        int actualViolationsCount = getViolationsCount(reportName);
        Assert.assertEquals(1, actualViolationsCount);
    }
```



![Image](https://github.com/dequelabs/axe-core-maven-html/assets/47409579/bd812d6e-c41a-41c9-b3e4-cc091e3b2901)

2. axe-core-maven-html_selenium is working fine with the lazy loaded iframes it is not hanging and giving `frame-title` violations and `frame-tested` incomplete results

TestScript:

```
@Test
    public void scanPageAndSaveResultsToJsonFileTest() throws IOException, OperationNotSupportedException {
        String reportName = "iframesTest";
        this.webDriver.get("http://localhost:8081/iframesfixture.html");
        Results result = new AxeBuilder().analyze(webDriver);
        AxeReporter.writeResultsToJsonFile("src/test/java/results/"+reportName, result);
        int actualViolationsCount = getViolationsCount(reportName);
        Assert.assertEquals(1, actualViolationsCount);
    }
```



![Image](https://github.com/dequelabs/axe-core-maven-html/assets/47409579/c56feb5b-5d3a-46e5-a646-ce8e92d7a7b3)


## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-maven-html_|
|**Version** | _4.8.0_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8  & Windows11 _ |
|**BrowserDetails**|_Chrome Version 118.0.5993.70  (Official Build) (64-bit) & Firefox 118.0.1_|

**Comment by padmavemulapati** [comment]
Verified with the latest `axe-core-maven-html_Playwright - 4.8.1-SNAPSHOT/playwright-4.8.1-20240109.201525-1` 
created a test file for unloaded iframes(lazy loaded iframes)

1. axe-core-maven-html_playwright is working fine with the lazy loaded iframes it is not hanging and giving `frame-title` violations.
Note: Here As per changes other than selenium packages, we can see a `frame-title` violation` only not a `frame-tested` incomplete result, as this lazy loaded iframes fix is done for selenium.

Test script:

```
 @Test
    public void scanPageAndSaveResultsToJsonFileTest() throws IOException {
        String reportName = "iframesTest.json";
        page.navigate("http://localhost:8081/iframesfixture.html");
        AxeBuilder axeBuilder = new AxeBuilder(page);
        AxeResults axeResults = axeBuilder.analyze();
        Reporter reporter = new Reporter().JSONStringify(axeResults, reportName);
        int actualViolationsCount = getViolationsCount(reportName);
        Assert.assertEquals(1, actualViolationsCount);
    }
```



<img width="536" alt="image" src="https://github.com/dequelabs/axe-core-maven-html/assets/47409579/b62ca5f3-1c0c-4fac-8fe7-cd42c52da25a">


2. axe-core-maven-html_selenium is working fine with the lazy loaded iframes it is not hanging and giving `frame-title` violations and `frame-tested` incomplete results

TestScript:

```
@Test
    public void scanPageAndSaveResultsToJsonFileTest() throws IOException, OperationNotSupportedException {
        String reportName = "iframesTest";
        this.webDriver.get("http://localhost:8081/iframesfixture.html");
        Results result = new AxeBuilder().analyze(webDriver);
        AxeReporter.writeResultsToJsonFile("src/test/java/results/"+reportName, result);
        int actualViolationsCount = getViolationsCount(reportName);
        Assert.assertEquals(1, actualViolationsCount);
    }
```


<img width="514" alt="image" src="https://github.com/dequelabs/axe-core-maven-html/assets/47409579/9987cf51-eed8-465c-a0a2-e4c34765c737">


## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-maven-html_|
|**Version** | _ 4.8.1-SNAPSHOT/4.8.1-20240109.201525-1_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8  & Windows11 _ |
|**BrowserDetails**|_Chrome Version 120.0.6099.129  (Official Build) (64-bit) & Firefox 121.1_|
