### ISSUE TITLE
Unable to run builder.analyze even after following this solution - https://github.com/dequelabs/axe-core-maven-html/blob/develop/selenium/error-handling.md

### ISSUE THREAD

**Issue by AakashNanda** [dequelabs/axe-core-maven-html#328]
Hi ,

I was facing issue and got error message as 
Axe failed. Refer below link for solution.
https://github.com/dequelabs/axe-core-maven-html/blob/develop/selenium/error-handling.md.

I followed the suggestion and ensured that my drivers are up to date and Allow pop up setting is also enabled when chrome launched but still facing same error.
Code snippet.
AxeBuilder builder = new AxeBuilder();
                Results results = builder.analyze(this.webUtil.driver);

Could you  please look into this issue. Please let me know if any additional details needed.

**Comment by Zidious** [comment]
Hey @AakashNanda,

Are you able to provide the URL you're testing as well as the full test snippet where you run axe?

**Comment by AakashNanda** [comment]
String url = webUtil.getCurrentUrl();

                    AxeBuilder builder = new AxeBuilder();
                    Results results = builder.analyze(webUtil.driver);
                    List<Rule> violations = results.getViolations();

**Comment by Zidious** [comment]
Sorry @AakashNanda, this snippet doesn't tell me much, can you provide the below: 

1. Can you provide the full URL you're testing? 
2. What does your entire test case look like for the URL you're testing?
3. What is the full stack trace error?

**Comment by AakashNanda** [comment]
Can you provide the full URL you're testing? https://www.physiciansmutual.com/web/home
What does your entire test case look like for the URL you're testing? I am scanning this page to check for any violations related to accessibility.
	public boolean checkAxeIssue() throws Exception {
		webUtil.get("https://www.physiciansmutual.com/web/home");
		PMA11y pma11y = new PMA11y();
		pma11y.checkAccessibility();
		return true;
	}
public boolean checkAccessibility() {
String url = webUtil.getCurrentUrl();

                    AxeBuilder builder = new AxeBuilder();
                    Results results = builder.analyze(webUtil.driver);
                    List<Rule> violations = results.getViolations();
return true;
}


What is the full stack trace error?
result = {StackTraceElement[21]@13099} 
 0 = {StackTraceElement@12998} "com.deque.html.axecore.selenium.AxeBuilder.analyzePost43x(AxeBuilder.java:606)"
  declaringClass = "com.deque.html.axecore.selenium.AxeBuilder"
  methodName = "analyzePost43x"
  fileName = "AxeBuilder.java"
  lineNumber = 606
 1 = {StackTraceElement@12999} "com.deque.html.axecore.selenium.AxeBuilder.analyzeRawContext(AxeBuilder.java:505)"
  declaringClass = "com.deque.html.axecore.selenium.AxeBuilder"
  methodName = "analyzeRawContext"
  fileName = "AxeBuilder.java"
  lineNumber = 505
 2 = {StackTraceElement@13000} "com.deque.html.axecore.selenium.AxeBuilder.analyze(AxeBuilder.java:463)"
  declaringClass = "com.deque.html.axecore.selenium.AxeBuilder"
  methodName = "analyze"
  fileName = "AxeBuilder.java"
  lineNumber = 463
 3 = {StackTraceElement@13001} "com.pmaf.web.PMA11y.checkAccessibility(PMA11y.java:26)"
  declaringClass = "com.pmaf.web.PMA11y"
  methodName = "checkAccessibility"
  fileName = "PMA11y.java"
  lineNumber = 26
 4 = {StackTraceElement@13002} "com.pmaf.aef.staticpages.WEB.checkAxeIssue(WEB.java:108)"
  declaringClass = "com.pmaf.aef.staticpages.WEB"
  methodName = "checkAxeIssue"
  fileName = "WEB.java"
  lineNumber = 108
 5 = {StackTraceElement@13003} "com.pmaf.web.C254.checkAxeIssue(C254.java:17)"
  declaringClass = "com.pmaf.web.C254"
  methodName = "checkAxeIssue"
  fileName = "C254.java"
  lineNumber = 17
 6 = {StackTraceElement@13004} "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
  declaringClass = "sun.reflect.NativeMethodAccessorImpl"
  methodName = "invoke0"
  fileName = "NativeMethodAccessorImpl.java"
  lineNumber = -2
 7 = {StackTraceElement@13005} "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
  declaringClass = "sun.reflect.NativeMethodAccessorImpl"
  methodName = "invoke"
  fileName = "NativeMethodAccessorImpl.java"
  lineNumber = 62
 8 = {StackTraceElement@13006} "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
  declaringClass = "sun.reflect.DelegatingMethodAccessorImpl"
  methodName = "invoke"
  fileName = "DelegatingMethodAccessorImpl.java"
  lineNumber = 43
 9 = {StackTraceElement@13007} "java.lang.reflect.Method.invoke(Method.java:498)"
  declaringClass = "java.lang.reflect.Method"
  methodName = "invoke"
  fileName = "Method.java"
  lineNumber = 498
 10 = {StackTraceElement@13008} "org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)"
  declaringClass = "org.testng.internal.MethodInvocationHelper"
  methodName = "invokeMethod"
  fileName = "MethodInvocationHelper.java"
  lineNumber = 133
 11 = {StackTraceElement@13009} "org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)"
  declaringClass = "org.testng.internal.TestInvoker"
  methodName = "invokeMethod"
  fileName = "TestInvoker.java"
  lineNumber = 584
 12 = {StackTraceElement@13010} "org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)"
  declaringClass = "org.testng.internal.TestInvoker"
  methodName = "invokeTestMethod"
  fileName = "TestInvoker.java"
  lineNumber = 172
 13 = {StackTraceElement@13011} "org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)"
  declaringClass = "org.testng.internal.MethodRunner"
  methodName = "runInSequence"
  fileName = "MethodRunner.java"
  lineNumber = 46
 14 = {StackTraceElement@13012} "org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)"
  declaringClass = "org.testng.internal.TestInvoker$MethodInvocationAgent"
  methodName = "invoke"
  fileName = "TestInvoker.java"
  lineNumber = 804
 15 = {StackTraceElement@13013} "org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)"
  declaringClass = "org.testng.internal.TestInvoker"
  methodName = "invokeTestMethods"
  fileName = "TestInvoker.java"
  lineNumber = 145
 16 = {StackTraceElement@13014} "org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)"
  declaringClass = "org.testng.internal.TestMethodWorker"
  methodName = "invokeTestMethods"
  fileName = "TestMethodWorker.java"
  lineNumber = 146
 17 = {StackTraceElement@13015} "org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)"
  declaringClass = "org.testng.internal.TestMethodWorker"
  methodName = "run"
  fileName = "TestMethodWorker.java"
  lineNumber = 128
 18 = {StackTraceElement@13016} "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
  declaringClass = "java.util.concurrent.ThreadPoolExecutor"
  methodName = "runWorker"
  fileName = "ThreadPoolExecutor.java"
  lineNumber = 1149
 19 = {StackTraceElement@13017} "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
  declaringClass = "java.util.concurrent.ThreadPoolExecutor$Worker"
  methodName = "run"
  fileName = "ThreadPoolExecutor.java"
  lineNumber = 624
 20 = {StackTraceElement@13018} "java.lang.Thread.run(Thread.java:748)"
  declaringClass = "java.lang.Thread"
  methodName = "run"
  fileName = "Thread.java"
  lineNumber = 748

**Comment by Zidious** [comment]
Using the latest version of our Selenium package, I was not able to replicate this issues, see below: 

```xml
<dependency>
    <groupId>com.deque.html.axe-core</groupId>
    <artifactId>selenium</artifactId>
    <version>4.7.0</version>
</dependency>
```

```java
import com.deque.html.axecore.results.Results;
import com.deque.html.axecore.results.Rule;
import com.deque.html.axecore.selenium.AxeBuilder;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.List;

public class Main {
  public static void main(final String[] args) throws InterruptedException {

    WebDriver driver = new ChromeDriver();
    AxeBuilder builder = new AxeBuilder();

    driver.get("https://www.physiciansmutual.com/web/home");

    Results results = builder.analyze(driver);

    List<Rule> violations = results.getViolations();

    for (Rule rule : violations) {
      System.out.printf("Rule: %s - Desc: %s%n", rule.getId(), rule.getHelp());
    }

    driver.quit();
  }
}
```

Output: 
```
Rule: page-has-heading-one - Desc: Page should contain a level-one heading
```

**Comment by AakashNanda** [comment]
Its working fine with latest version. 4.7.0
Thanks for the support
