### ISSUE TITLE
Pin axe-core version to patch updates only (`~`)

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-maven-html#360]
A user recently ran into a problem where [they installed an api at v4.7](https://github.com/dequelabs/axe-core-npm/issues/830) but got axe-core version v4.8 (causing some confusion on why rules weren't running that should have been). Turns out that we've been pinning to axe-core using `^` which allows minor updates. This goes against our goal of version locking the apis to the major and minor version of axe-core that is used in the api. 

We'll fix this by using `~` to patch pin our axe-core dependency.

**Comment by padmavemulapati** [comment]
Validated with the Canary build - `Playwright-4.7.0-SNAPSHOT`

![image](https://github.com/dequelabs/axe-core-maven-html/assets/47409579/56838106-04fc-4e78-8fe0-c982be8e344c)


Earlier for `axe-core` dependency we used to add the dependency with `^`, which allows minor updates -

![image](https://github.com/dequelabs/axe-core-maven-html/assets/47409579/822ff776-608f-4cd5-bb69-a5cb98a5adab)


Now we are pinning the axe-core version to strict to the updated version.

![image](https://github.com/dequelabs/axe-core-maven-html/assets/47409579/aadbc425-664f-4a97-9f2d-c93fc826b3b1)

This is now holding `axe-core_4.8.2` , we can see in the results when the test page is scanned:

for axe-core-maven-html-selenium package:
<img width="1165" alt="image" src="https://github.com/dequelabs/axe-core-maven-html/assets/47409579/ff875f35-fbee-4331-892d-bf953ef1b574">

for axe-core-maven-html-playwright package:
![image](https://github.com/dequelabs/axe-core-maven-html/assets/47409579/e60e3839-c80f-4779-9895-ea5601eef2a9)

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-maven-html_|
|**Version** | _4.7.0-SNAPSHOT_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8  & Windows11 _ |
|**BrowserDetails**|_Chrome Version 117.0.5938.88 (Official Build) (64-bit) & Firefox 117.0_|
