### ISSUE TITLE
Allow axe to run on just the page source instead of injecting into DOM

### ISSUE THREAD

**Issue by mohanraj-r** [dequelabs/axe-core-maven-html#39]
Is it possible to run axe on a given page source html string instead of having to inject itself into the DOM? If this is possible, could it enable making WebDriver as an optional dependency e.g. have alternate `Builder()` APIs in which we pass in the HTML source instead of the webdriver?

**Comment by mohanraj-r** [comment]
Noticing that `AXE.inject()` is a public static method that injects the axe-core js lib into the page using WebDriver `executeScript()`. What is the use case for this API outside/alongside `Builder`? 
Because I see it is also being used by `Builder.analyze()` -> `Builder.execute()` -> `AXE.inject()`. But then its not checked if the axe script has already been injected - leading me to wonder about the use-case of `AXE.inject()`.

**Comment by dythebs** [comment]
I'm also looking for ways to test HTML string directly, now I use `((RemoteWebDriver) driver).executeScript("document.write(arguments[0]);", html);`

**Comment by jeeyyy** [comment]
@mohanraj-r would appreciate if you update to 4.0 axe-core-maven-html & let us know if this is still an issue.

Please reopen if you stumble upon the issue again. Thank you.
