### ISSUE TITLE
Empty tab is opened and closed in browser in the analyzePost43x private method of AxeBuilder.java class

### ISSUE THREAD

**Issue by tvtester** [dequelabs/axe-core-maven-html#391]
Following method is opening empty tab in the browser at the code:  `String prevWindow = WebDriverExtensions.openAboutBlank(webDriver);` and `WebDriverExtensions.closeAboutBlank(webDriver, prevWindow);`

`private Results analyzePost43x(final WebDriver webDriver, final Object rawContextArg) {
    String rawOptionsArg = getOptions().equals("{}")
        ? AxeReporter.serialize(runOptions) : getOptions();

    ArrayList<Object> partialResults;
    try {
      partialResults = runPartialRecursive(webDriver, rawOptionsArg, rawContextArg, true);
    } catch (RuntimeException re) {
      if (re.getMessage().contains("Unable to inject axe script")) {
        throw re;
      }
      return buildErrorResults(re);
    }

    String prevWindow = WebDriverExtensions.openAboutBlank(webDriver);
    injectAxe(webDriver);
    Object resResponse;
    try {
      resResponse = WebDriverInjectorExtensions.executeScript(webDriver, finishRunScript, partialResults);
    } catch (Exception e) {
      throw new RuntimeException("axe.finishRun failed. Please check out https://github.com/dequelabs/axe-core-maven-html/blob/develop/error-handling.md", e);

    }
    WebDriverExtensions.closeAboutBlank(webDriver, prevWindow);
    Results res = objectMapper.convertValue(resResponse, Results.class);

    return res;
  }`

Product: 

Expectation: Empty or additional tab should not be open in the browser

Actual: Driver is opening empty tab and close it, though there is no need of it

Motivation: 

<pre><code>
axe-core version: X.Y.Z
axe-webdriver, extension or other integration version: X.Y.Z

Browser and Assistive Technology versions

For Tooling issues:
- Node version: XX  
- Platform:  
</code></pre>

**Comment by straker** [comment]
@tvtester We've identified the issue and will work on getting a fix in place that works for our supported versions of Selenium. Until then you can mitigate this issue by using [setLegacyMode(true)](https://github.com/dequelabs/axe-core-maven-html/tree/develop/selenium#axebuildersetlegacymodeboolean-legacymode) before analyzing. Just note that the legacy mode is deprecated and will be removed in v5.0.

**Comment by padmavemulapati** [comment]
Verified with the latest QA-Build (4.8.1-SNAPSHOT/4.8.1-20240109.201525-1) , With `Safari` driver we were able to run the `axe-core-maven-html` tests successfully. not seeing any exceptions or failures.

Code tested:

```
package com.deque;

import static com.deque.html.axecore.selenium.AxeReporter.getAxeResultString;
import static com.deque.html.axecore.selenium.AxeReporter.getReadableAxeResults;
import static org.junit.Assert.assertEquals;

import com.deque.html.axecore.providers.FileAxeScriptProvider;
import com.deque.html.axecore.results.CheckedNode;
import com.deque.html.axecore.results.Results;
import com.deque.html.axecore.results.Rule;
import com.deque.html.axecore.selenium.AxeBuilder;
import com.deque.html.axecore.selenium.AxeReporter;

import java.io.File;
import java.io.IOException;
import java.io.FileReader;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import javax.naming.OperationNotSupportedException;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;



import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import org.openqa.selenium.safari.SafariDriver;
/** The example tests using the updated files. */
public class SeleniumJavaTest {
    private WebDriver webDriver;
    static String rootPath = System.getProperty("user.dir");
    String baseUrl = "http://abcdcomputech.dequecloud.com/";
 /** Instantiate the WebDriver and navigate to the test site */
    @Before
    public void setUp() {
          webDriver = new SafariDriver();
       
    }

    /** Ensure we close the WebDriver after finishing */
    @After
    public void tearDown() {
       if (webDriver != null) {
            webDriver.quit();
        }
    }

    /** Basic test */
    @Test
    public void completePageScanTest() {
        this.webDriver.get(baseUrl);
        Results result = new AxeBuilder().analyze(webDriver);
        Assert.assertEquals(8, result.getViolations().size()); 
    }
public static int getViolationsCount(String reportName) {
        JSONParser parser = new JSONParser();
        String filePath = rootPath + File.separator + "src/test/java/results/"+ reportName  + ".json";
        int i=0;
        try {
            Object obj = parser.parse(new FileReader(filePath));
            JSONObject jsonObject = (JSONObject)obj;
            String url = (String)jsonObject.get("url");
            System.out.println("url: " + url);
            JSONArray violations = (JSONArray)jsonObject.get("violations");
            return violations.size();
            
        } catch(Exception e) {
            e.printStackTrace();
        }
       return i;
    }
}

```

![image](https://github.com/dequelabs/axe-core-maven-html/assets/47409579/50acafbe-8922-46dd-bf26-d8d9375563c1)

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Product**                | _axe-core-maven-html_|
|**Version** | _ 4.8.1-SNAPSHOT/4.8.1-20240109.201525-1_ |
| **OS-Details**      | _MAC- Intel Core i7 - 11.6.8  & Windows11 _ |
|**BrowserDetails**|_Chrome Version 120.0.6099.129  (Official Build) (64-bit) & Firefox 121.1_|

**Comment by idontusenumbers** [comment]
`selenium/standalone-chromium:148.0`
`com.deque.html.axe-core:selenium:4.11.3`
`org.seleniumhq.selenium:selenium-java:4.44.0` ,

I am seeing a lot of exceptions thrown by `axeBuilder.analyze(webDriver)`, the intermittent leftover empty tabs it leaves behind, or the tabs it is analyzing that it happens to intermittently close.

I wrote some code to identify and workaround these issues:
```
try {
	axeResults = axeBuilder.analyze(webDriver);
} finally {
	// let axe activity settle
	waitForLoad();
	
	// Clean up any extra tabs axeCore opened
	Set<String> windowHandles = webDriver.getWindowHandles();
	if (!windowHandles.contains(windowHandle)) {
		log.error(testShortName + " The expected tab doesnt exist");
		windowHandle = windowHandles.stream().toList().get(0);
	}
	windowHandles.remove(windowHandle);
	for (String handle : windowHandles) {
		try {
			webDriver.switchTo().window(handle);
			webDriver.close();
		} catch (NoSuchWindowException ex) {
			// probably already closed
		} catch (DevToolsException | TimeoutException ex) {
			// probably already closed
		}
	}
	webDriver.switchTo().window(windowHandle);
}
```
Along with test retry logic to throw out apparently-broken webdrivers, create new ones, and retry the tests.

Turning on legacy mode almost completely eliminates these issues.

**Comment by scottmries** [comment]
Thanks for this @idontusenumbers! I added a separate issue, and we should be working on it shortly.
