### ISSUE TITLE
allow analyze() to take in a list of WebElements

### ISSUE THREAD

**Issue by mohanraj-r** [dequelabs/axe-core-maven-html#40]
[axe-core context](https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#context-parameter) accepts "A NodeList such as returned by document.querySelectorAll."

When testing `axe.run()` manually in browser I found that it works with a list of HTMLElement references. But the selenium API allows analyzing only one WebElement at a time. When we want to analyze a list of WebElements, injecting axe-core into DOM using Selenium and running the analyze for each element becomes expensive. Would it be possible to have an API that accepts a list of WebElements? Is there any reason that wouldn't work? If not please let me know and if possible I can try and add the API.

@stephenmathieson

**Comment by stephenmathieson** [comment]
Can't you use the include/exclude API instead?

**Comment by mohanraj-r** [comment]
@stephenmathieson I tried to, but the include/exclude API uses CSS selectors and there seems to be no way to get the css selector from a selenium WebElement (apparently by design: https://stackoverflow.com/a/19843175, https://stackoverflow.com/a/31677984)

**Comment by stephenmathieson** [comment]
Right, but how are you getting those elements to begin with?

**Comment by mohanraj-r** [comment]
I am trying to integrate axe-selenium into a common test lib and how the elements are found is not under the lib's control - the tests can use any mechanism to find the elements.

**Comment by mohanraj-r** [comment]
Thanks @stephenmathieson 
Do you know how selenium's WebElement converts to dom's HTMLElement when control flows from selenium java to axe-core ? or how to test/debug the java to js data flow?

**Comment by stephenmathieson** [comment]
> Do you know how selenium's WebElement converts to dom's HTMLElement when control flows from selenium java to axe-core ?

What happens is:

1. The axe-core JavaScript code is injected into the Selenium page
1. We call `axe.run()`
1. We get back the JSON results from `axe.run()`
1. We wrap the JSON results with `org.json.JSONObject` and return it

So no, we do not convert from `WebElement` to `HTMLElement`.

**Comment by jeeyyy** [comment]
PR in place. Closing this issue.
