### ISSUE TITLE
Require QA consideration in PRs

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-maven-html#401]
Set up https://github.com/dequelabs/axe-api-team-public/blob/main/.github/actions/semantic-pr-footer-v1 so it will block a PR that does not have at least one of the following:

- There is a link to a valid issue in the description of the PR
- The words "QA NOTES" appear in the description of the PR
- The words "QA NOT NEEDED" appear in the description of the PR

**Comment by padmavemulapati** [comment]
Verified Github actions, work flow is defined for QA-required actions, can find in the below link:

https://github.com/dequelabs/axe-core-maven-html/blob/4e89037a874058a970567ebf62fc0b2fef7ee55f/.github/workflows/semantic-pr-footer.yml#L16

## Screenshot:

<img width="1320" alt="image" src="https://github.com/dequelabs/axe-core-maven-html/assets/47409579/b99304c4-f2be-48e2-b89c-73a88f2ebaa7">
