### ISSUE TITLE
Include / exclude is incorrectly passed to axe-core

### ISSUE THREAD

**Issue by riksmith** [dequelabs/axe-core-maven-html#42]
When I specify an "exclude" in the builder nothing seems to happen, the exclude is ignored.

I found this is caused by a flaw in the analyze() method. It incorrectly passes the include / exclude object as options param instead of context as stated in the axe-core docs.

Also it does not look like the case with only supplying excludes and no includes is properly handled. As per the axe-core docs I would not expect an "include" property to be set in the context, just the exclude property.

**Comment by stasek** [comment]
As well as not working properly a few include

**Comment by jeeyyy** [comment]
Fixed. Closing issue.
