### ISSUE TITLE
Create bug report and feature request issue templates in repo

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/axe-core-maven-html#445]
We need to make sure all information is captured when an issue is created. To doso, we will be utilizing Github Issue Templates 
.
Please create these two issue templates in this repo. They should be copied from our team repo:

- [x] https://github.com/dequelabs/axe-api-team/blob/main/.github/ISSUE_TEMPLATE/bug-report.md
- [x] https://github.com/dequelabs/axe-api-team/blob/main/.github/ISSUE_TEMPLATE/feature-request.md

Acceptance Criteria: When a new issue is created, it should show the option of choosing a Bug Report or Feature Request template to start from.

**Comment by padmavemulapati** [comment]
Verified that when we are going to create a new issue it is asking for "Bug Report" / "Feature Request" / "Report a security vulnerability" templates once we select required one it will gives the relevant template to create an issue


https://github.com/dequelabs/axe-core-maven-html/assets/47409579/5ea126d2-6b93-484b-a74b-e188b17ec520
