### ISSUE TITLE
Help running axe in existing java/selenium test 

### ISSUE THREAD

**Issue by Sajutii1994** [dequelabs/axe-core-maven-html#57]
im trying to run axe in existing java selenium test to get violations. Im using this dependency:
<dependency>
  <groupId>com.deque</groupId>
  <artifactId>axe-selenium</artifactId>
  <version>3.0</version>
  <scope>test</scope>
</dependency>
and im also using the axe.js under my test but what do i need to analyze multipule pages in one test?

**Comment by AdnoC** [comment]
To analyze multiple pages in a single test you have to analyze each individual page. We don't provide any batch analyzing capabilities.

**Comment by jeeyyy** [comment]
@Sajutii1994 this axe integration only allows to analyze one page at a time.

> Our paid version of axe DevTools allows multiple pages to be tested by integrating APIs into existing automated testing, or through Command Line tools. My colleague Kyle would be happy to discuss your specific use case if you'd like to learn more. You can reach him via email at: kyle.hartman@deque.com

**Comment by jeeyyy** [comment]
@Sajutii1994 I will close the issue given the above comment. Please feel free to open it if further discussion is necessary.
