### ISSUE TITLE
Question: Why has this project been renamed ?

### ISSUE THREAD

**Issue by mohanraj-r** [dequelabs/axe-core-maven-html#68]
Why has this project been renamed from `axe-selenium-java` to `axe-core-maven-html`

Why is there a new project https://github.com/dequelabs/axe-selenium-java? 
  - It doesn't have any history. Seems to be essentially a clone of this project with few modifications
  - It doesn't have a `develop` branch
  - It doesn't have github `Issues` enabled

**Comment by TroyWalshProf** [comment]
Note*  If this is actually moving the URL for the package really needs to be updated:
https://github.com/dequelabs/axe-core-maven-html/blob/96a6d3ff0f2be7403494de7fcb2d9dd9396770ef/pom.xml#L15
@WilcoFiers

**Comment by WilcoFiers** [comment]
Apologies for the slow response. I missed this issue. We are in the process of updating all of our axe packages to have greater consistency between them. This is part of a larger rebranding project that Deque is doing: https://www.deque.com/blog/deque-unifies-accessibility-software-under-axe/
