### ISSUE TITLE
Include axe-core by default

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/axe-core-maven-html#83]
This package should be able to run with a default version of axe-core, which needs to be in sync with the axe-core version. i.e. if it is on version axe-core-selenium 4.1, that will have axe-core version 4.1 as a default. You should still be able to pass a source for different versions of axe-core.

**Comment by padmavemulapati** [comment]
Verified on part of axe-core-maven-html QAing

**Comment by straker** [comment]
No docs required
